name: pull-upstream

on:
  push:
    branches:
      - develop

jobs:
  pull_upstream:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      # @TODO - Move this to after the git diff so it's only done if there's
      #         any changes to pull in. That will also require stashing of the
      #         changes, so the site can install before being upgraded.
      - name: Setup ddev
        uses: jonaseberle/github-action-setup-ddev@v1
        with:
          autostart: false
      - name: Start ddev 👨🏻‍💻
        run: cd drupal && ddev start
      - name: Install Drupal 👨🏻‍💻
        run: cd drupal && ddev composer install && ddev drush -y tome:install

      - name: Checkout Upstream (realityloop/foundry) 🛎
        uses: actions/checkout@master
        with:
          repository: realityloop/foundry
          ref: develop
          path: upstream

      - name: Copy config from upstream
        run: rm -rf drupal/config/sync && cp -rf upstream/config/sync drupal/config/sync
      - name: Copy composer.* from upstream
        run: cp upstream/composer.* drupal
      - name: Cleanup upstream
        run: rm -rf upstream
      # - run: git diff # @todo: exit-code 0 if no diff

      - name: Update from upstream 👨🏻‍💻
        run: cd drupal && ddev composer install && ddev drush updb -y && ddev drush cim -y
      - name: Tome export 👨🏻‍💻
        run: cd drupal && ddev drush -y en tome_sync && ddev drush -y tome:export

      - run: git diff && git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: develop
          body: ''
          branch: upstream
          commit-message: "chore: update from upstream"
          delete-branch: true
          title: "chore: update from upstream"
      - name: Pull Request output
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
